### PR TITLE
Rebase onto Wolfi

### PR DESCRIPTION
**Pull request by TheFutonEng**
Looking to get some feedback on how this PR is rebasing onto Wolfi.  Based on the notes in #16 , there are fewer vulnerabilities in the Wolfi image.  There are still some little things to sort out, like getting session manager in the image and finding suitable replacements for some other packages in the Wolfi APK repo.

### CODE REVIEW

**Comment by RothAndrew** [comment]
Thinking through how we can release and test this as a release candidate before merging it to main. Ideas? My initial thought is to either cut a tag from this branch, or change the target branch to something else like `wolfi-rc` and then cut a tag from that.

**Comment by RothAndrew** [comment]
@TheFutonEng what are your thoughts on how we will get back the various packages/tools that are currently commented out?

**Comment by TheFutonEng** [comment]
> @TheFutonEng what are your thoughts on how we will get back the various packages/tools that are currently commented out?

@RothAndrew, that's still pending.  I happened to stumble upon the proper pip package by accident which is called `py3-pip` in the Wolfi apk repo and `python3-pip` in the Rocky repo.  Hoping to resolve most, if not all, of the commented-out packages by just finding the proper package name in the Wolfi repo.  There may be some that have to be pulled in another way.

> Thinking through how we can release and test this as a release candidate before merging it to main. Ideas? My initial thought is to either cut a tag from this branch, or change the target branch to something else like wolfi-rc and then cut a tag from that.

I think I prefer the latter option.  Is there anything in the current GH action setup that would make one option better?

**Comment by RothAndrew** [comment]
> Is there anything in the current GH action setup that would make one option better?
Not that I can think of. Either option should work fine.

**Comment by TheFutonEng** [comment]
Since Wolfi did not significantly reduce the number of vulnerabilities in the image, going to close this PR.

**Comment by RothAndrew** [comment]
Sounds goo. Is there stuff you want to save in the branch or can we delete it?

**Pull request closed without merging**
